from __future__ import annotations

from typing import Literal, Protocol

from ._handles import FileHandle
from ._types import OpenMode

RecoveryIntent = Literal["auto", "abort"]


class BackendTransaction(Protocol):
    @property
    def has_open_writers(self) -> bool: ...

    def open_handle(self, key: str, mode: OpenMode = "r", *, encoding: str | None = None) -> FileHandle: ...
    def delete(self, key: str) -> None: ...
    def assert_all_writers_closed(self) -> None: ...
    def discard_open_writers(self) -> None: ...
    def register_child_repo(self, child_repo_path: str) -> None: ...
    def unregister_child_repo(self, child_repo_path: str) -> None: ...
    def mark_child_prepared(self, child_repo_path: str) -> None: ...
    def mark_child_committed(self, child_repo_path: str) -> None: ...
    def prepare(self) -> None: ...
    def commit(self) -> None: ...
    def detach_for_recovery(self) -> None: ...
    def rollback(self) -> None: ...


class Backend(Protocol):
    def open_committed_handle(
        self,
        repo_locator: str,
        key: str,
        mode: OpenMode = "r",
        *,
        encoding: str | None = None,
    ) -> FileHandle: ...
    def child_repo_locator(self, repo_locator: str, child_repo_path: str) -> str: ...
    def begin(self, repo_locator: str, parent_tx: BackendTransaction | None = None) -> BackendTransaction: ...
    def recover(self, repo_locator: str, *, intent: RecoveryIntent = "auto") -> None: ...
    def debug_status(self, repo_locator: str) -> object: ...
