from __future__ import annotations

from typing import Literal, Protocol

from ._blob_backend import BlobBackend
from ._handles import FileHandle
from ._types import OpenMode


RepoId = str
RecoveryIntent = Literal["auto", "abort"]


class JournalTransaction(Protocol):
    @property
    def has_open_writers(self) -> bool: ...
    @property
    def root_tx_id(self) -> str: ...
    @property
    def coordination_root_locator(self) -> str: ...
    @property
    def is_prepared(self) -> bool: ...

    def open_handle(self, key: str, mode: OpenMode = "r", *, encoding: str | None = None) -> FileHandle: ...
    def delete(self, key: str) -> None: ...
    def assert_all_writers_closed(self) -> None: ...
    def discard_open_writers(self) -> None: ...
    def register_child_repo(self, child_repo_path: str) -> None: ...
    def unregister_child_repo(self, child_repo_path: str) -> None: ...
    def mark_child_open(self, child_repo_path: str) -> None: ...
    def mark_child_prepared(self, child_repo_path: str) -> None: ...
    def authorize_root_publication(self) -> None: ...
    def reopen_prepared(self) -> None: ...
    def prepare(self) -> None: ...
    def mark_committing(self) -> None: ...
    def publish_prepared(self) -> None: ...
    def clear_committed(self) -> None: ...
    def commit(self) -> None: ...
    def detach_for_recovery(self) -> None: ...
    def rollback(self) -> None: ...


class JournalBackend(Protocol):
    @property
    def identity(self) -> str: ...

    def prepare_repo_open(
        self,
        repo_locator: RepoId,
        blob_backend: BlobBackend,
        *,
        parent_repo_locator: RepoId | None = None,
        child_repo_path: str | None = None,
    ) -> RepoId: ...

    def begin(
        self,
        repo_locator: RepoId,
        blob_backend: BlobBackend,
        parent_tx: JournalTransaction | None = None,
        coordination_root_locator: RepoId | None = None,
    ) -> JournalTransaction: ...

    def recover(
        self,
        repo_locator: RepoId,
        blob_backend: BlobBackend,
        *,
        intent: RecoveryIntent = "auto",
        coordination_root_locator: RepoId | None = None,
    ) -> None: ...

    def require_clear_for_read(self, repo_locator: RepoId, blob_backend: BlobBackend) -> None: ...

    def debug_status(self, repo_locator: RepoId, blob_backend: BlobBackend) -> object: ...


__all__ = [
    "JournalBackend",
    "JournalTransaction",
    "RecoveryIntent",
    "RepoId",
]
